include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  
    prefer_single_quotes: true
    avoid_positional_boolean_parameters: false
    avoid_bool_literals_in_conditional_expressions: false



