name: acm_arts
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  rxdart: ^0.27.4
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  animated_text_kit: ^4.2.1
  floating_action_bubble: ^1.1.4
  animated_image_list: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  
flutter:
  uses-material-design: true
